import { ModelInfo } from '../store/useAppStore'

// Qwen Model Catalog Registry - All models from Qwen_OpenVINO
// RAG models (embedding/reranker) are excluded for beta — see export filter below.
const ALL_QWEN_MODELS: ModelInfo[] = [
  // ============================================
  // Qwen3-VL - Vision Language Model
  // ============================================
  {
    id: 'qwen3-vl-4b',
    name: 'Qwen3-VL-4B-Instruct',
    family: 'Qwen3-VL',
    featureType: 'vision_assistant',
    parameterSize: '4B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 8,
    recommendedDevice: 'GPU',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-vl-4b-ov',
    diskSizeGb: 8.5,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 18.2,
      tokensPerSecond: 52.3,
      loadTimeMs: 2400,
      ramUsedMb: 4200,
      gpuUsedMb: 3800,
      npuStatus: 'not_applicable',
    },
  },
  {
    id: 'qwen3-vl-8b',
    name: 'Qwen3-VL-8B-Instruct',
    family: 'Qwen3-VL',
    featureType: 'vision_assistant',
    parameterSize: '8B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 16,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-vl-8b-ov',
    diskSizeGb: 16.2,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 24.5,
      tokensPerSecond: 38.7,
      loadTimeMs: 3200,
      ramUsedMb: 7800,
      gpuUsedMb: 7200,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen2.5-VL - Vision Language Model (Legacy)
  // ============================================
  {
    id: 'qwen25-vl-3b',
    name: 'Qwen2.5-VL-3B-Instruct',
    family: 'Qwen2.5-VL',
    featureType: 'vision_assistant',
    parameterSize: '3B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2.5-VL-3B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 6,
    recommendedDevice: 'GPU',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen25-vl-3b-ov',
    diskSizeGb: 6.1,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 12.8,
      tokensPerSecond: 68.4,
      loadTimeMs: 1800,
      ramUsedMb: 3200,
      gpuUsedMb: 2900,
      npuStatus: 'not_applicable',
    },
  },
  {
    id: 'qwen25-vl-7b',
    name: 'Qwen2.5-VL-7B-Instruct',
    family: 'Qwen2.5-VL',
    featureType: 'vision_assistant',
    parameterSize: '7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2.5-VL-7B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 12,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen25-vl-7b-ov',
    diskSizeGb: 14.3,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 21.3,
      tokensPerSecond: 42.1,
      loadTimeMs: 2800,
      ramUsedMb: 6500,
      gpuUsedMb: 5900,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen2-VL - Vision Language Model (Legacy)
  // ============================================
  {
    id: 'qwen2-vl-2b',
    name: 'Qwen2-VL-2B-Instruct',
    family: 'Qwen2-VL',
    featureType: 'vision_assistant',
    parameterSize: '2B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 4,
    recommendedDevice: 'AUTO',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen2-vl-2b-ov',
    diskSizeGb: 4.2,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 10.5,
      tokensPerSecond: 78.2,
      loadTimeMs: 1200,
      ramUsedMb: 2100,
      gpuUsedMb: 1800,
      npuStatus: 'not_applicable',
    },
  },
  {
    id: 'qwen2-vl-7b',
    name: 'Qwen2-VL-7B-Instruct',
    family: 'Qwen2-VL',
    featureType: 'vision_assistant',
    parameterSize: '7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 12,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen2-vl-7b-ov',
    diskSizeGb: 13.8,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 22.1,
      tokensPerSecond: 40.5,
      loadTimeMs: 2900,
      ramUsedMb: 6200,
      gpuUsedMb: 5600,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen2.5-Omni - Omni-modal Model
  // ============================================
  {
    id: 'qwen25-omni-7b',
    name: 'Qwen2.5-Omni-7B',
    family: 'Qwen2.5-Omni',
    featureType: 'omni_assistant',
    parameterSize: '7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2.5-Omni-7B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8'],
    recommendedRamGb: 16,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen25-omni-7b-ov',
    diskSizeGb: 15.8,
    benchmark: {
      device: 'GPU',
      precision: 'INT8',
      firstTokenLatency: 25.3,
      tokensPerSecond: 35.2,
      loadTimeMs: 3500,
      ramUsedMb: 8200,
      gpuUsedMb: 7500,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen3-ASR - Automatic Speech Recognition
  // ============================================
  {
    id: 'qwen3-asr-06b',
    name: 'Qwen3-ASR-0.6B',
    family: 'Qwen3-ASR',
    featureType: 'voice_assistant',
    parameterSize: '0.6B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-ASR-0.6B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 2,
    recommendedDevice: 'AUTO',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-asr-06b-ov',
    diskSizeGb: 1.2,
    benchmark: {
      device: 'NPU',
      precision: 'INT8',
      firstTokenLatency: 8.5,
      tokensPerSecond: 95.2,
      loadTimeMs: 600,
      ramUsedMb: 1100,
      gpuUsedMb: 0,
      npuStatus: 'available',
    },
  },
  {
    id: 'qwen3-asr-17b',
    name: 'Qwen3-ASR-1.7B',
    family: 'Qwen3-ASR',
    featureType: 'voice_assistant',
    parameterSize: '1.7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-ASR-1.7B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 4,
    recommendedDevice: 'GPU',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-asr-17b-ov',
    diskSizeGb: 3.4,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 11.2,
      tokensPerSecond: 72.8,
      loadTimeMs: 900,
      ramUsedMb: 2200,
      gpuUsedMb: 1800,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen3-TTS - Text-to-Speech
  // ============================================
  {
    id: 'qwen3-tts-06b',
    name: 'Qwen3-TTS-12Hz-0.6B-Base',
    family: 'Qwen3-TTS',
    featureType: 'voice_output',
    parameterSize: '0.6B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-TTS-12Hz-0.6B-Base',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 2,
    recommendedDevice: 'AUTO',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-tts-06b-ov',
    diskSizeGb: 1.1,
    benchmark: {
      device: 'NPU',
      precision: 'INT8',
      firstTokenLatency: 6.2,
      tokensPerSecond: 110.5,
      loadTimeMs: 500,
      ramUsedMb: 950,
      gpuUsedMb: 0,
      npuStatus: 'available',
    },
  },
  {
    id: 'qwen3-tts-17b',
    name: 'Qwen3-TTS-12Hz-1.7B-Base',
    family: 'Qwen3-TTS',
    featureType: 'voice_output',
    parameterSize: '1.7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-TTS-12Hz-1.7B-Base',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8'],
    recommendedRamGb: 4,
    recommendedDevice: 'GPU',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-tts-17b-ov',
    diskSizeGb: 3.2,
    benchmark: {
      device: 'GPU',
      precision: 'INT8',
      firstTokenLatency: 9.8,
      tokensPerSecond: 85.3,
      loadTimeMs: 800,
      ramUsedMb: 2000,
      gpuUsedMb: 1600,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen3-Embedding - Text Embedding
  // ============================================
  {
    id: 'qwen3-embedding-06b',
    name: 'Qwen3-Embedding-0.6B',
    family: 'Qwen3-Embedding',
    featureType: 'rag_assistant',
    parameterSize: '0.6B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Embedding-0.6B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 2,
    recommendedDevice: 'AUTO',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-embedding-06b-ov',
    diskSizeGb: 1.0,
    benchmark: {
      device: 'NPU',
      precision: 'INT8',
      firstTokenLatency: 3.2,
      tokensPerSecond: 145.8,
      loadTimeMs: 400,
      ramUsedMb: 800,
      gpuUsedMb: 0,
      npuStatus: 'available',
    },
  },
  {
    id: 'qwen3-embedding-4b',
    name: 'Qwen3-Embedding-4B',
    family: 'Qwen3-Embedding',
    featureType: 'rag_assistant',
    parameterSize: '4B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Embedding-4B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 8,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-embedding-4b-ov',
    diskSizeGb: 7.8,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 5.8,
      tokensPerSecond: 98.5,
      loadTimeMs: 700,
      ramUsedMb: 3800,
      gpuUsedMb: 3200,
      npuStatus: 'not_applicable',
    },
  },
  {
    id: 'qwen3-embedding-8b',
    name: 'Qwen3-Embedding-8B',
    family: 'Qwen3-Embedding',
    featureType: 'rag_assistant',
    parameterSize: '8B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Embedding-8B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 16,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-embedding-8b-ov',
    diskSizeGb: 15.5,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 8.2,
      tokensPerSecond: 72.4,
      loadTimeMs: 1200,
      ramUsedMb: 7500,
      gpuUsedMb: 6800,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen3-Reranker - Text Reranker
  // ============================================
  {
    id: 'qwen3-reranker-06b',
    name: 'Qwen3-Reranker-0.6B',
    family: 'Qwen3-Reranker',
    featureType: 'rag_assistant',
    parameterSize: '0.6B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Reranker-0.6B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 2,
    recommendedDevice: 'AUTO',
    npuStatus: 'supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-reranker-06b-ov',
    diskSizeGb: 1.0,
    benchmark: {
      device: 'NPU',
      precision: 'INT8',
      firstTokenLatency: 2.8,
      tokensPerSecond: 155.2,
      loadTimeMs: 350,
      ramUsedMb: 750,
      gpuUsedMb: 0,
      npuStatus: 'available',
    },
  },
  {
    id: 'qwen3-reranker-4b',
    name: 'Qwen3-Reranker-4B',
    family: 'Qwen3-Reranker',
    featureType: 'rag_assistant',
    parameterSize: '4B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Reranker-4B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 8,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-reranker-4b-ov',
    diskSizeGb: 7.6,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 4.5,
      tokensPerSecond: 105.8,
      loadTimeMs: 650,
      ramUsedMb: 3600,
      gpuUsedMb: 3000,
      npuStatus: 'not_applicable',
    },
  },
  {
    id: 'qwen3-reranker-8b',
    name: 'Qwen3-Reranker-8B',
    family: 'Qwen3-Reranker',
    featureType: 'rag_assistant',
    parameterSize: '8B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Reranker-8B',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 16,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen3-reranker-8b-ov',
    diskSizeGb: 15.2,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 6.8,
      tokensPerSecond: 82.5,
      loadTimeMs: 1100,
      ramUsedMb: 7200,
      gpuUsedMb: 6500,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen-Image - Text-to-Image Generation
  // ============================================
  {
    id: 'qwen-image',
    name: 'Qwen-Image',
    family: 'Qwen-Image',
    featureType: 'image_generation',
    parameterSize: 'Unknown',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen-Image',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8'],
    recommendedRamGb: 16,
    recommendedDevice: 'GPU',
    npuStatus: 'not-supported',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen-image-ov',
    diskSizeGb: 12.5,
    benchmark: {
      device: 'GPU',
      precision: 'INT8',
      firstTokenLatency: 125.0,
      tokensPerSecond: 8.2,
      loadTimeMs: 4500,
      ramUsedMb: 9500,
      gpuUsedMb: 8800,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // LLM Agent - Function Calling
  // ============================================
  {
    id: 'llm-agent-functioncall',
    name: 'Qwen LLM Agent (Function Calling)',
    family: 'Qwen3-Coder',
    featureType: 'coding_agent',
    parameterSize: '7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Coder-7B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 12,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/llm-agent-functioncall-ov',
    diskSizeGb: 14.8,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 19.5,
      tokensPerSecond: 48.2,
      loadTimeMs: 2600,
      ramUsedMb: 6800,
      gpuUsedMb: 6200,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // LLM Agent - MCP Tools
  // ============================================
  {
    id: 'llm-agent-mcp',
    name: 'Qwen LLM Agent (MCP Tools)',
    family: 'Qwen3-Coder',
    featureType: 'coding_agent',
    parameterSize: '7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Coder-7B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 12,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/llm-agent-mcp-ov',
    diskSizeGb: 14.8,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 19.5,
      tokensPerSecond: 48.2,
      loadTimeMs: 2600,
      ramUsedMb: 6800,
      gpuUsedMb: 6200,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // LLM Agent - ReAct LangChain
  // ============================================
  {
    id: 'llm-agent-react',
    name: 'Qwen LLM Agent (ReAct + LangChain)',
    family: 'Qwen3-Coder',
    featureType: 'personal_assistant',
    parameterSize: '7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen3-Coder-7B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8', 'INT4'],
    recommendedRamGb: 12,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/llm-agent-react-ov',
    diskSizeGb: 14.8,
    benchmark: {
      device: 'GPU',
      precision: 'INT4',
      firstTokenLatency: 19.5,
      tokensPerSecond: 48.2,
      loadTimeMs: 2600,
      ramUsedMb: 6800,
      gpuUsedMb: 6200,
      npuStatus: 'not_applicable',
    },
  },

  // ============================================
  // Qwen2-Audio - Audio Understanding
  // ============================================
  {
    id: 'qwen2-audio-7b',
    name: 'Qwen2-Audio-7B-Instruct',
    family: 'Qwen2-Audio',
    featureType: 'voice_assistant',
    parameterSize: '7B',
    license: 'Apache-2.0',
    sourceUrl: 'https://huggingface.co/Qwen/Qwen2-Audio-7B-Instruct',
    packageType: 'safetensors',
    precisionOptions: ['FP16', 'INT8'],
    recommendedRamGb: 12,
    recommendedDevice: 'GPU',
    npuStatus: 'unknown',
    openvinoStatus: 'converted',
    benchmarkStatus: 'completed',
    lastUpdated: '2026-07-04',
    state: 'ready',
    localOpenVinoPath: 'models/qwen2-audio-7b-ov',
    diskSizeGb: 13.2,
    benchmark: {
      device: 'GPU',
      precision: 'INT8',
      firstTokenLatency: 28.5,
      tokensPerSecond: 32.8,
      loadTimeMs: 3100,
      ramUsedMb: 7200,
      gpuUsedMb: 6500,
      npuStatus: 'not_applicable',
    },
  },
]

export const QWEN_MODEL_CATALOG: ModelInfo[] = ALL_QWEN_MODELS.filter(
  (m) => m.featureType !== 'rag_assistant'
)

// Model feature types with display info
export const MODEL_FEATURE_TYPES = {
  personal_assistant: {
    label: 'Personal Assistant',
    icon: 'MessageSquare',
    color: 'text-edge-cyan',
    bgColor: 'bg-edge-cyan/10',
    borderColor: 'border-edge-cyan/30',
  },
  coding_agent: {
    label: 'Coding Agent',
    icon: 'Code2',
    color: 'text-qwen-violet',
    bgColor: 'bg-qwen-violet/10',
    borderColor: 'border-qwen-violet/30',
  },
  vision_assistant: {
    label: 'Vision Assistant',
    icon: 'Eye',
    color: 'text-status-warning',
    bgColor: 'bg-status-warning/10',
    borderColor: 'border-status-warning/30',
  },
  voice_assistant: {
    label: 'Voice Assistant',
    icon: 'Mic',
    color: 'text-status-error',
    bgColor: 'bg-status-error/10',
    borderColor: 'border-status-error/30',
  },
  voice_output: {
    label: 'Text-to-Speech',
    icon: 'Volume2',
    color: 'text-status-error',
    bgColor: 'bg-status-error/10',
    borderColor: 'border-status-error/30',
  },
  omni_assistant: {
    label: 'Omni-modal',
    icon: 'Layers',
    color: 'text-edge-blue',
    bgColor: 'bg-edge-blue/10',
    borderColor: 'border-edge-blue/30',
  },
  image_generation: {
    label: 'Image Generation',
    icon: 'Image',
    color: 'text-qwen-purple',
    bgColor: 'bg-qwen-purple/10',
    borderColor: 'border-qwen-purple/30',
  },
} as const

// Model families with display info
export const MODEL_FAMILIES = {
  'Qwen3-VL': { label: 'Qwen3-VL', description: 'Latest Vision Language Model' },
  'Qwen2.5-VL': { label: 'Qwen2.5-VL', description: 'Vision Language Model' },
  'Qwen2-VL': { label: 'Qwen2-VL', description: 'Legacy Vision Language Model' },
  'Qwen2.5-Omni': { label: 'Qwen2.5-Omni', description: 'Omni-modal Understanding' },
  'Qwen3-ASR': { label: 'Qwen3-ASR', description: 'Automatic Speech Recognition' },
  'Qwen3-TTS': { label: 'Qwen3-TTS', description: 'Text-to-Speech' },
  'Qwen3-Embedding': { label: 'Qwen3-Embedding', description: 'Text Embedding' },
  'Qwen3-Reranker': { label: 'Qwen3-Reranker', description: 'Text Reranking' },
  'Qwen-Image': { label: 'Qwen-Image', description: 'Text-to-Image Generation' },
  'Qwen3-Coder': { label: 'Qwen3-Coder', description: 'Coding & Agent Models' },
  'Qwen2-Audio': { label: 'Qwen2-Audio', description: 'Audio Understanding' },
} as const

// Device recommendations based on model size
export function getRecommendedDevice(modelSize: string): string {
  const sizeNum = parseFloat(modelSize)
  if (sizeNum <= 2) return 'AUTO'
  if (sizeNum <= 7) return 'GPU'
  return 'GPU'
}

// RAM recommendation
export function getRecommendedRam(modelSize: string): number {
  const sizeNum = parseFloat(modelSize)
  if (sizeNum <= 1) return 2
  if (sizeNum <= 4) return 8
  if (sizeNum <= 8) return 16
  return 24
}

// Model state labels
export const MODEL_STATE_LABELS: Record<string, string> = {
  'not-installed': 'Not Installed',
  'downloading': 'Downloading...',
  'downloaded': 'Downloaded',
  'verifying': 'Verifying...',
  'verified': 'Verified',
  'converting': 'Converting...',
  'converted': 'Converted',
  'quantizing': 'Quantizing...',
  'optimized': 'Optimized',
  'benchmarking': 'Benchmarking...',
  'ready': 'Ready to Load',
  'failed': 'Failed',
  'loaded': 'Loaded',
  'running': 'Running',
}

// OpenVINO status labels
export const OPENVINO_STATUS_LABELS: Record<string, string> = {
  'not-converted': 'Not Converted',
  'converting': 'Converting...',
  'converted': 'Converted',
  'failed': 'Conversion Failed',
}

// Benchmark status labels
export const BENCHMARK_STATUS_LABELS: Record<string, string> = {
  'not-run': 'Not Run',
  'running': 'Running...',
  'completed': 'Completed',
  'failed': 'Failed',
}